---
title: "Viz 3"
output: github_document
---

```{r setup , include = FALSE}
library(tidyverse)
library(ggridges)
library(p8105.datasets)
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
#library(readxl)
#library(haven)
```

Import the weather data 
```{r}
data("weather_df")
weather_df =
  weather_df|>
  mutate (month = floor_date(date, unit = "month"))
```

Make a plot
```{r}
weather_df |>
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```

Check on the extreme values
```{r}
weather_df |>
  filter(prcp > 1000) # need some background data. Thinking about where the values come from.
```

Look at data again
```{r}

weather_df |>
  filter (tmax >=20, tmax <= 30)|>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() 
```

## Add group 
and count by name

```{r}
weather_df |>
  group_by(name) |>
  summarize(
    n = n()
  )
```
add count by month

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n = n()
  )
```

group by both name and month
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    n = n()
  )
# try n distinc function
weather_df |>
  group_by(month) |>
  summarize(
    n = n_distinct(date)
  )
```

You can count directly
```{r}
weather_df |>
  count(name)
```

## More interesting
```{r}
weather_df |>
  group_by(month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE) # remove na values when calculating mean
  )
```
 Group by both name and month
```{r}
weather_df |>
  group_by(name, month) |> # order can be a matter inn some cases
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE) # remove na values when calculating mean
  )
``` 

Plotting the frame that just grouped and summarized

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  )|>
  ggplot (aes(x = month, y = mean_tmax, color = name)) +
  geom_point()+
  geom_line()
```

Formatting the results
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |>
  knitr::kable(digits = 2)
```

